packages:
  - "apps/*"
  - "packages/*"

allowBuilds:
  esbuild: true
  protobufjs: false

minimumReleaseAgeExclude:
  - "@univer-cli/*"
  - "@univerjs/*"
  - "@univerjs-pro/*"

overrides:
  react: 19.3.0
  react-dom: 19.3.0
